### PR TITLE
Update Flightdeck to include Add-on SDK 1.11

### PR DESCRIPTION
**Pull request by KWierso**
This should be everything needed to get 1.11 up on Builder. We're shipping 1.11 on Tuesday, so if we can get this stuff ready before then, that'd be awesome.

### CODE REVIEW

**Comment by seanmonstar** [comment]
You can /cc @seanmonstar to catch my attention also.

Should this update the settings also, for `LOWEST_APPROVED_SDK` and `TEST_SDK`?

**Comment by KWierso** [comment]
Yes it should! It's just that one file that needs bumped, yes?

**Comment by seanmonstar** [comment]
That's the only one, yes.

**Comment by KWierso** [comment]
Thanks, Sean!

**Pull request merged**
