### PR TITLE
Shipyard IDE

### PR DESCRIPTION
**Pull request by seanmonstar**
This is the first step in moving towards [Shipyard](/seanmonstar/Shipyard).

Practically everything that made the editor work in JavaScript has been moved in the Shipyard architecture. The `File` classes are now Shipyard Models, which means they will eventually use `ServerSync` (pending on the api branch), and have data binding available.

Some files have been deleted that didn't make sense anymore, and other had not been used in a year.

Every part of the new `ide` app that doesn't still rely on MooTools has tests written. Being on production also requires these files to be minified, which is a plus over the current situation (nothing is minified).

After jingo lands, I'd like to add a `shipyard` helper that will replace the current script tags in the templates.

For development, you simply need to `git submodule update --init`, since Shipyard is a submodule. To run the tests, you would need to have nodejs and npm installed. Once they are, you would `cd media/lib/shipyard` and then `npm link`. Then, from the `ide` folder, you can run `shipyard test` to watch the tests pass.

### CODE REVIEW

**Comment by seanmonstar** [comment]
@clouserw: The way I expect most developers to use Shipyard is to `npm link` it, making the `shipyard` bin globally available. However, @oremj tells me we can't use npm directly, so how would I accomplish what I need on the admin box?

`npm link` would also download [uglify-js](/mishoo/UglifyJS), [dryice](/mozilla/dryice), and [commander.js](/visionmedia/commander.js).

commander is used in the `shipyard` bin, but `shipyard build` ends up calling `script/build.js` with some arguments, so I could probably just have the script called on it's own, removing the need for commander. However, the build.js still needs to be able to `require('uglify-js')` and `require('dryice')`.

**Comment by clouserw** [comment]
Probably some combination of our migrations/ stuff and our vendor lib.  I don't have much experience with npm or the alternatives that IT wants us to use, /cc @oremj to give us answers.  We might need to huddle up on irc!

**Comment by oremj** [comment]
Hey, there are two options:

1) I can just make an rpm for whatever node lib you need to use.
2) node has a vendor type of thing already built in. If you put your dependencies in PROJECT_ROOT/node_modules/{DEP1,DEP2,DEP3}/node_modules/DEP1_DEP1.... it will just work.

**Comment by seanmonstar** [comment]
Yes, I know about node_modules. Should I just npm link the files 
locally, and commit them to the repo?

**Comment by oremj** [comment]
That's fine with me. I'm also fine with making an rpm. Up to you.

**Pull request merged**
