### PR TITLE
Bug 661619 sync amo deleted users

### PR DESCRIPTION
**Pull request by zalun**
If a profile is saved with the existing nickname, old one is updated from AMO

If update from AMO is returning None, it will mean that the user is deleted.
We are deleting the user from builder as well.

For existing multiple profiles - the check is done in the same place
error was displayed - in person.managers get_user_by_nickname with the
same solution.

BaseModel run_update_setters is now checking if field to update actually exists.
This is because update_from_AMO was called on every Profile save.

Duplicated email column removed from update_to_AMO, also person.tests
looks a bit nicer

### CODE REVIEW

**Comment by pennyfx** [comment]
Why delete the user?   Can we just deactivate their account?  Also, if we don't want their packages shown in search then we can switch them to private.   Then if for some reason they sign back up with AMO, then all their work will still exist.

What do you think?

**Comment by zalun** [comment]
They will never have the same user id on AMO - and that's how we sync the accounts

**Comment by pennyfx** [comment]
Oh, I just looked at the code.  For Auth we query AMO by email address, but for update_from_AMO we query by id (user.username).    I don't understand why we would do this.

**Comment by zalun** [comment]
We agreed to give the user ability to take over the Builder account using a different AMO account during login procedure. There is no need to sync on AMO user id, instead email will be used.

**Pull request closed without merging**
